---
- name: Change the global Python version (1)
  become: yes
  become_user: "{{ linux_user }}"
  ansible.builtin.command: |
    bash -c "{{ pyenv_user_home }}/.pyenv/bin/pyenv global \"{{ pyenv_global }}\""
  changed_when: false
  failed_when: PYENV_GLOBAL is failed
  register: PYENV_GLOBAL
  when:
    - linux_user is defined

- name: Change the global Python version (2)
  ansible.builtin.command: |
    bash -c "{{ pyenv_user_home }}/.pyenv/bin/pyenv global \"{{ pyenv_global }}\""
  changed_when: false
  failed_when: PYENV_GLOBAL is failed
  register: PYENV_GLOBAL
  when:
    - linux_user is not defined
