---
- name: Check whether ruby is installed
  ansible.builtin.command: ruby -v
  register: ruby_installed
  changed_when: false
  ignore_errors: true
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"

- name: Install packages required to build ruby.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - gcc
    - gdbm-devel
    - git
    - libffi-devel
    - make
    - ncurses-devel
    - openssl-devel
    - readline-devel
    - wget
    - zlib-devel
  when: ruby_installed is failed

- name: Download ruby.
  ansible.builtin.get_url:
    url: "{{ ruby_download_url }}"
    dest: "{{ workspace }}/ruby-{{ ruby_version }}.tar.gz"
    mode: 0755
    owner: root
    group: root
  when: ruby_installed is failed

- name: Extract ruby.
  ansible.builtin.unarchive:
    src: "{{ workspace }}/ruby-{{ ruby_version }}.tar.gz"
    dest: "{{ workspace }}/"
    copy: false
    mode: 0755
  when: ruby_installed is failed

- name: Create Makefile.
  ansible.builtin.command: ./configure --enable-shared
  args:
    chdir: "{{ workspace }}/ruby-{{ ruby_version }}"
  when: ruby_installed is failed

- name: Build ruby 1/2.
  community.general.make:
    chdir: "{{ workspace }}/ruby-{{ ruby_version }}"
    params:
      PREFIX: "{{ ruby_make_prefix }}"
  when: ruby_installed is failed

- name: Build ruby 2/2.
  community.general.make:
    chdir: "{{ workspace }}/ruby-{{ ruby_version }}"
    target: install
    params:
      PREFIX: "{{ ruby_make_prefix }}"
  when: ruby_installed is failed

- name: Add ruby symlinks.
  ansible.builtin.file:
    src: "/usr/local/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: true
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby
  when: ruby_installed is failed
