---
- name: Install packages required to build ruby.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2
    - gcc
    - gdbm-devel
    - git
    - libffi-devel
    - make
    - ncurses-devel
    - openssl-devel
    - readline-devel
    - wget
    - zlib-devel

- name: Download ruby.
  ansible.builtin.get_url:
    url: "{{ ruby_download_url }}"
    dest: "{{ workspace }}/ruby-{{ ruby_version }}.tar.gz"

- name: Extract ruby.
  ansible.builtin.unarchive:
    src: "{{ workspace }}/ruby-{{ ruby_version }}.tar.gz"
    dest: "{{ workspace }}/"
    copy: false
    mode: 0755

- name: Build ruby.
  ansible.builtin.command: >
    {{ item }}
    chdir={{ workspace }}/ruby-{{ ruby_version }}
    creates=/usr/local/bin/ruby
  with_items:
    - "{{ ruby_source_configure_command }}"
    - make
    - make install

- name: Add ruby symlinks.
  ansible.builtin.file:  # noqa 208
    src: "/usr/local/bin/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: true
  with_items:
    - erb
    - gem
    - irb
    - rake
    - rdoc
    - ruby
