---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Check whether ruby is installed
      ansible.builtin.shell: |
        ruby --version
      register: ruby_installed
      changed_when: false

    - name: Make sure Ruby is installed
      ansible.builtin.debug:
        var: ruby_installed

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
