---
name: build
on:
  deployment:
    branches:
      - main
  push:
    paths-ignore:
      - '**.md'

jobs:
  ansible-lint:
    uses: github-actions-reusable-workflows/ansible-lint/.github/workflows/workflows.yml@main

  molecule-centos7:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos7:latest

  molecule-centos-stream8:
    uses: github-actions-reusable-workflows/molecule-docker/.github/workflows/workflows.yml@main
    with:
      molecule-image: ghcr.io/docker-hub-tm/ansible-test/centos-stream8:latest

  trailing-whitespace:
    name: Find Trailing Whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: harupy/find-trailing-whitespace@master

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Execute yamllint
        run: yamllint *

      - name: Show yamllint version
        run: |
          yamllint --version \
          | GREP_COLORS='mt=01;34' egrep --color=always '[[:digit:]]' \
          | GREP_COLORS='mt=01;34' egrep --color=always '\.' \
          | GREP_COLORS='mt=01;33' egrep --color=always 'yamllint.* '
